apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  jwt-secret: {{ .Values.env.JWT_SECRET | quote }}
  stripe-secret-key: {{ .Values.env.STRIPE_SECRET_KEY | quote }}
  stripe-webhook-secret: {{ .Values.env.STRIPE_WEBHOOK_SECRET | quote }}
